"""empty message

Revision ID: ac32c7328a2f
Revises: b4f95c0beeab
Create Date: 2023-10-31 16:11:22.885704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac32c7328a2f'
down_revision = 'b4f95c0beeab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Catalog',
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=255), nullable=False),
    sa.Column('itemDescription', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availableQuantity', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('SKU')
    )
    op.create_table('User',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Customer',
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creditCard', sa.String(length=19), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zipCode', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('customerID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('SubscriptionTemplate',
    sa.Column('templateID', sa.Integer(), nullable=False),
    sa.Column('planName', sa.String(length=255), nullable=False),
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('frequencyInMonths', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SKU'], ['Catalog.SKU'], ),
    sa.PrimaryKeyConstraint('templateID')
    )
    op.create_table('Address',
    sa.Column('addressID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('addressType', sa.Enum('Shipping', 'Billing'), nullable=False),
    sa.Column('addressLine1', sa.String(length=255), nullable=False),
    sa.Column('addressLine2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zipCode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customerID'], ['Customer.customerID'], ),
    sa.PrimaryKeyConstraint('addressID')
    )
    op.create_table('Orders',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orderStatus', sa.Enum('PENDING', 'SHIPPED', 'INVOICED', 'RETURNED', 'SUBSCRIBED'), nullable=True),
    sa.ForeignKeyConstraint(['customerID'], ['Customer.customerID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_table('LineItems',
    sa.Column('lineItemID', sa.Integer(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SKU'], ['Catalog.SKU'], ),
    sa.ForeignKeyConstraint(['orderID'], ['Orders.orderID'], ),
    sa.PrimaryKeyConstraint('lineItemID')
    )
    op.create_table('OrderDetails',
    sa.Column('orderDetailID', sa.Integer(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=255), nullable=False),
    sa.Column('itemDescription', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priceAtTimeOfOrder', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['SKU'], ['Catalog.SKU'], ),
    sa.ForeignKeyConstraint(['orderID'], ['Orders.orderID'], ),
    sa.PrimaryKeyConstraint('orderDetailID')
    )
    op.create_table('SubscriptionOrders',
    sa.Column('subscriptionOrderID', sa.Integer(), nullable=False),
    sa.Column('templateID', sa.Integer(), nullable=True),
    sa.Column('orderID', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('planName', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['orderID'], ['Orders.orderID'], ),
    sa.ForeignKeyConstraint(['templateID'], ['SubscriptionTemplate.templateID'], ),
    sa.PrimaryKeyConstraint('subscriptionOrderID')
    )
    op.create_table('Shipment',
    sa.Column('shipmentID', sa.Integer(), nullable=False),
    sa.Column('lineItemID', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PICK', 'PACK', 'SHIP'), nullable=True),
    sa.ForeignKeyConstraint(['lineItemID'], ['LineItems.lineItemID'], ),
    sa.PrimaryKeyConstraint('shipmentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shipment')
    op.drop_table('SubscriptionOrders')
    op.drop_table('OrderDetails')
    op.drop_table('LineItems')
    op.drop_table('Orders')
    op.drop_table('Address')
    op.drop_table('SubscriptionTemplate')
    op.drop_table('Customer')
    op.drop_table('User')
    op.drop_table('Catalog')
    # ### end Alembic commands ###
